{{- if .Values.mcp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: mcp-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp
  {{- with .Values.mcp.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mcp.service.type }}
  selector:
    {{- include "bunkerweb.selectorLabels" . | nindent 4 }}
    bunkerweb.io/component: "mcp"
  ports:
    - name: http
      port: {{ .Values.mcp.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
